collegestore/a3h1collegestore/urls.py
from django.urls import path

from a3h1collegestore import views

app_name = 'a3h1collegestore'

urlpatterns=[
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),

]

collegestore/collegestore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path ('',include('a3h1collegestore.urls')),
    path('credentials/',include('credentials.urls')),
    path('order/',include('order.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

collegestore/credentials/urls.py
from django.urls import path
from credentials import views

app_name ='credentials'

urlpatterns=[
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout')
]

collegestore/order/urls.py
from django.urls import path

from order import views

app_name ='order'

urlpatterns=[
    path('',views.order_create_view,name='order_create'),
    path('ajax/load_course/',views.load_courses,name='ajax_load_courses')
    ]

collegestore/a3h1collegestore/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=250, unique=True)

    def __str__(self):
        return '{}'.format(self.name)

class Course(models.Model):
    name = models.CharField(max_length=250,unique=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.name)

class Message(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    subject = models.CharField(max_length=250)
    message = models.TextField()
    def __str__(self):
        return self.name

collegestore/credentials/models.py
from django.db import models

# Create your models here.
class Material(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return '{}'.format(self.name)

collegestore/order/models.py
from django.db import models

from a3h1collegestore.models import Department, Course

import json

from credentials.models import Material

# Create your models here.

PPS = [
    ('FOR_ENQUIRY' ,'For enquiry'),
    ('PLACE_ORDER','Place order'),
    ('RETURN','Return')
]

GND = [
    ('MALE','Male'),
    ('FEMALE','Female'),
    ('OTHER','Other')
]






class Order(models.Model):
    name = models.CharField(max_length=250)
    DOB = models.DateField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    gender = models.CharField(max_length=25,choices=GND)
    phone_number = models.CharField(max_length=10)
    mail_id = models.EmailField()
    address = models.TextField()
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, blank=True, null=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, blank=True, null=True)
    purpose = models.CharField(max_length=250, choices=PPS)
    materials = models.ManyToManyField(Material)

    def __str__(self):
        return '{}'.format(self.name)


    

collegestore/a3h1collegestore/forms.py
from django import forms
from .models import Message
class messageForm(forms.ModelForm):
    class Meta:
        model=Message
        fields=['name','email','subject','Message']

collegestore/credentials/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password1','password2')

collegestore/order/forms.py
from django import forms

from credentials.models import Material
from order.models import Order
from a3h1collegestore.models import Course

class DateInput(forms.DateInput):
    input_type = 'date'


class RadioSelect(forms.RadioSelect):
    input_type = 'radio'

class CheckboxSelectMultiple(forms.CheckboxSelectMultiple):
    input_type = 'checkbox'


class OrderCreationForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name','DOB','age','gender','phone_number','mail_id','address','department','course','purpose','materials']
        materials = forms.ModelMultipleChoiceField(
            queryset=Material.objects.all(),
        )
        widgets = {
            'DOB': DateInput(),
            'gender': RadioSelect(),
            'materials':CheckboxSelectMultiple()
        }



    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Course.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department_id=department_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.order_by('name')

collegestore/a3h1collegestore/views.py
from django.shortcuts import render

from a3h1collegestore.models import Message
from order.models import Order


# Create your views here.
def index(request):
    return render(request, 'index.html')
def about(request):
    return render(request, 'about.html')

def contact(request):
    if request.method=="POST":
        name=request.POST.get('name')
        email=request.POST.get('email')
        subject=request.POST.get('subject')
        message=request.POST.get('message')
        messages=Message(name=name,email=email,subject=subject,message=message)
        messages.save()
        from django.contrib import messages
        messages.success(request, 'Message sent successfully')
    return render(request,'contact.html')

collegestore/credentials/views.py
from django.contrib import messages, auth
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from credentials.forms import CustomUserCreationForm





def register(request):
    form = CustomUserCreationForm()
    if request.method == 'POST':

        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, "Registered successfully")
            return redirect('credentials:login')
        else:
            form = CustomUserCreationForm()
    return render(request, 'register.html',{'form':form})



def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
                auth.login(request,user)
                messages.info(request, "successfully logged in")
                return render(request,'store.html')
        else:
                messages.info(request,"Invalid login credentials")
                return render(request,'login.html')
    return render(request,'login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

collegestore/order/views.py
from django.contrib import messages
from django.shortcuts import render

from order.models import Order



from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import OrderCreationForm
from .models import Order
from a3h1collegestore.models import Course


def order_create_view(request):
    form = OrderCreationForm()
    if request.method == 'POST':
        form = OrderCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, "order created successfully")
            return redirect('order:order_create')
    return render(request, 'shop.html', {'form': form})



# # AJAX
def load_courses(request):
    department_id = request.GET.get('department_id')
    courses = Course.objects.filter(department_id=department_id).all()
    return render(request, 'course_dropdown_list_options.html', {'courses': courses})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)

collegestore/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>a3h1collegestore</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Bethany
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/bethany-free-onepage-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container">
      <div class="header-container d-flex align-items-center justify-content-between">
        <div class="logo">
          <h1 class="text-light"><a href="index.html"><span>A3H1 College Store</span></a></h1>
          <!-- Uncomment below if you prefer to use an image logo -->
          <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav id="navbar" class="navbar">
          <ul>
            <li><a class="nav-link scrollto active" href="{% url 'a3h1collegestore:index' %}">Home</a></li>
            <li><a class="nav-link scrollto" href="{% url 'a3h1collegestore:about' %}">About</a></li>
            <li><a class="nav-link scrollto" href="{% url 'a3h1collegestore:contact' %}">Contact</a></li>
            <li class="dropdown"><a href="#"><span>Departments</span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                <li class="dropdown"><a href="https://en.wikipedia.org/wiki/Bachelor_of_Engineering"><span>Engineering</span></a></li>
                <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Science">Science</a></li>
                <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Commerce">Commerce</a></li>
                <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Mathematics">Mathematics</a></li>
                <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Arts">Arts</a></li>
              </ul>
            </li>
            {% if user.is_authenticated %}
            <li class="getstarted scrollto bg-info"> Hello {{user.username}} </li>
            <li><a class="getstarted scrollto bg-secondary" href="{% url 'order:order_create' %}">Order Now</a></li>
            <li><a class="getstarted scrollto bg-danger" href="{% url 'credentials:logout' %}">Logout</a></li>
            {% else %}
            <li><a class="getstarted scrollto bg-secondary" href="{% url 'credentials:register' %}">Register</a></li>
            <li ><a class="getstarted scrollto" href="{% url 'credentials:login' %}">Login</a></li>
            {% endif %}
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

      </div><!-- End Header Container -->
    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container text-center position-relative" data-aos="fade-in" data-aos-delay="200">
      <h1>Welcome to <strong>A3H1 College Store</strong></h1>
      <h2>We are providing college store services through online</h2>
      <a href="{% url 'credentials:login' %}" class="btn-get-started scrollto">Get Started</a>
    </div>
  </section><!-- End Hero -->

<section id="about" class="about">
      <div class="container bg-success text-white">

        <div class="row gy-4 justify-content-center">
          <div class="col-lg-4">
            <img src="{% static 'assets/img/profile-img.jpg' %}" class="img-fluid p-4" alt="">
            <img src="{% static 'assets/img/student-img.jpg' %}" class="img-fluid p-4" alt="">
          </div>
          <div class="col-lg-5 content">
            <h2>College Store</h2>
            <p class="fst-italic py-3">
              We have everything for your studies
            </p>
            <div class="row">
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-chevron-right text-white"></i> <strong>Working:</strong> <span>8AM - 6PM</span></li>
                  <li><i class="bi bi-chevron-right text-white"></i> <strong>Phone:</strong> <span>+91 0000 000 000</span></li>
                  <li><i class="bi bi-chevron-right text-white"></i> <strong>City:</strong> <span>Palakkad, KERALA</span></li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul>
                  <li><i class="bi bi-chevron-right text-white"></i> <strong>Email:</strong> <span>a3h1collegestore@gmail.com</span></li>
                </ul>
              </div>
            </div>
            <p class="py-5">
              Our Team Always There To Fulfill Your Needs
            </p>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->


<footer id="footer">



    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start justify-content-center">
        <div class="copyright">
          &copy; Copyright <strong><span>A3H1 College Store</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bethany-free-onepage-bootstrap-theme/ -->
          Designed by <a href="">A3H1</a>
        </div>
      </div>

    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>

collegestore/templates/course_dropdown_list_options.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.name }}</option>
{% endfor %}
</body>
</html>

collegestore/templates/shop.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>a3h1collegestore</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/favicon.png' %}" rel="icon">
  <link href="{% static 'assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Bethany
  * Updated: Mar 10 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/bethany-free-onepage-bootstrap-theme/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container">
      <div class="header-container d-flex align-items-center justify-content-between">
        <div class="logo">
          <h1 class="text-light"><a href="index.html"><span>A3H1 College Store</span></a></h1>
          <!-- Uncomment below if you prefer to use an image logo -->
          <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav id="navbar" class="navbar">
          <ul>
            <li><a class="nav-link scrollto active" href="{% url 'a3h1collegestore:index' %}">Home</a></li>
            <li><a class="nav-link scrollto" href="{% url 'a3h1collegestore:about' %}">About</a></li>
            <li><a class="nav-link scrollto" href="{% url 'a3h1collegestore:contact' %}">Contact</a></li>
<!--            <li><a class="nav-link scrollto " href="{% url 'credentials:register' %}">Register</a></li>-->
<!--            <li><a class="nav-link scrollto" href="#team">Team</a></li>-->
             <li class="dropdown"><a href="#"><span>Departments</span> <i class="bi bi-chevron-down"></i></a>
              <ul>
                <li class="dropdown"><a href="https://en.wikipedia.org/wiki/Bachelor_of_Engineering"><span>Engineering</span></a>
                  <ul>
<!--                    <li><a href="#">M.E</a></li><i class="bi bi-chevron-right"></i>-->
<!--                    <li><a href="#">C.E</a></li>-->
<!--                    <li><a href="#">C.S</a></li>-->
<!--                    <li><a href="#">E.E.E</a></li>-->
<!--                    <li><a href="#">E.C.E</a></li>-->
                  </ul>
                </li>
                <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Science">Science</a></li>
                <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Commerce">Commerce</a></li>
                <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Mathematics">Mathematics</a></li>
                <li><a href="https://en.wikipedia.org/wiki/Bachelor_of_Arts">Arts</a></li>
              </ul>
            </li>
<!--            <li><a class="getstarted scrollto" href="{% url 'a3h1collegestore:contact' %}">Log out</a></li>-->
<!--            <li><a class="getstarted scrollto" href="{% url 'a3h1collegestore:index' %}">Log In</a></li>-->
            {% if user.is_authenticated %}
            <li class="getstarted scrollto bg-info"> Hello {{user.username}} </li>
            <li><a class="getstarted scrollto bg-danger" href="{% url 'credentials:logout' %}">Logout</a></li>
            {% else %}
            <li><a class="getstarted scrollto bg-secondary" href="{% url 'credentials:register' %}">Register</a></li>
<!--            <li ><a class="getstarted scrollto" href="{% url 'credentials:login' %}">Login</a></li>-->
            {% endif %}
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

      </div><!-- End Header Container -->
    </div>
  </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container text-center position-relative" data-aos="fade-in" data-aos-delay="200">
      <h1>Welcome to <strong>A3H1 College Store</strong></h1>
      <h2>We are providing college store services through online</h2>
      <a href="" class="btn-get-started scrollto">Get Started</a>
    </div>
  </section><!-- End Hero -->


  <main id="main">
  <section>
<!--    <div>-->
<!--      <center>-->
<!--        <form method="post" enctype="multipart/form-data">-->
<!--        {% csrf_token %}-->
<!--          <input type="text" name="name" placeholder="Enter your Name"><br><br>-->
<!--          <label><strong>DOB : </strong></label>-->
<!--          <input type="date" name="DOB" ><br><br>-->
<!--          <input type="number" name="age" placeholder="Enter your age"><br><br>-->
<!--          <label><strong>Gender : </strong></label>-->
<!--          <input type="radio" name="gender" id="male" value="male">-->
<!--          <label for="male">Male</label>-->
<!--          <input type="radio" name="gender" id="female">-->
<!--          <label for="female">Female</label>-->
<!--          <input type="radio" name="gender" id="other">-->
<!--          <label for="other">Other</label><br><br>-->

<!--          <input type="text" name="phone_number" placeholder="Enter your phone number"><br><br>-->
<!--          <input type="email" name="mail_id" placeholder="Enter your mail id"><br><br>-->

<!--          <label><strong>Department : </strong></label>-->
<!--          <select name="department">-->
<!--            <option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->
<!--            {% for dep in links %}-->
<!--            <option value="{{dep.name }}">{{ dep.name }}</option>-->
<!--            {% endfor %}-->

<!--          </select><br><br>-->

<!--          <label><strong>Course : </strong></label>-->
<!--          <select name="course">-->
<!--            <option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->
<!--            {% for course in link_c %}-->
<!--            <option value="{{ course.name }}">{{ course.name }}</option>-->
<!--            {% endfor %}-->
<!--          </select><br><br>-->

<!--          <label><strong>Purpose : </strong></label>-->
<!--          <select name="purpose">-->
<!--            <option value="None">Choose</option>-->
<!--            <option value="for enquiry">For Enquiry</option>-->
<!--            <option value="place order">Place Order</option>-->
<!--            <option value="return">Return</option>-->
<!--          </select><br><br>-->

<!--          <h5><strong>Materials Provide </strong></h5>-->
<!--          <input type="checkbox" name="materials_provide" value="text_book">-->
<!--          <label>Text Books</label>-->
<!--          <input type="checkbox" name="materials_provide">-->
<!--          <label>Note Book</label>-->
<!--          <input type="checkbox" name="materials_provide">-->
<!--          <label>Pen</label>-->
<!--          <input type="checkbox" name="materials_provide">-->
<!--          <label>Exam Papers</label>-->
<!--          <input type="checkbox" name="materials_provide">-->
<!--          <label>Uniform</label>-->
<!--          <input type="checkbox" name="materials_provide">-->
<!--          <label>Gift card</label><br><br>-->

<!--          <center>-->
<!--            <input class="btn btn-success" type="submit" name="submit" value="submit">-->
<!--          </center>-->

<!--        </form>-->
<!--      </center>-->

<!--    </div>-->

    <div class="container">
    <div class="row">
        <center>
        <form method="post" id="orderForm"  enctype="multipart/form-data" data-courses-url="{% url 'order:ajax_load_courses' %}" >
        {% csrf_token %}
            <div class="col-md-8 d-inline-block align-stretch text-white bg-success p-4" >
                <div class="p-3">
                  {% for msg in messages %}
                  <h3 class="text text-white"><center>{{msg}} <i class="bi bi-check-circle-fill"></i></center></h3>
                  {% endfor %}
                </div>
                {{ form.as_p }}

            </div>
            <div class="col-md-8 d-inline-block align-stretch p-4 ">
                <input type="submit" class="btn btn-success" value="Submit"><br><br>
            </div>
        </form>




        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
          <script>
              $("#id_department").change(function () {
                  const url = $("#orderForm").attr("data-courses-url");  // get the url of the `load_cities` view
                  const departmentId = $(this).val();  // get the selected country ID from the HTML input

                  $.ajax({                       // initialize an AJAX request
                      url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
                      data: {
                          'department_id': departmentId       // add the country id to the GET parameters
                      },
                      success: function (data) {   // `data` is the return of the `load_cities` view function
                          $("#id_course").html(data);  // replace the contents of the city input with the data that came from the server
                          /*

                          let html_data = '<option value="">---------</option>';
                          data.forEach(function (course) {
                              html_data += `<option value="${corse.id}">${course.name}</option>`
                          });
                          console.log(html_data);
                          $("#id_course").html(html_data);

                          */
                      }
                  });

              });
          </script>
        </center>
    </div>
    </div>

  </section>


  </main>

  <footer id="footer">
    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>A3H1 College Store</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/bethany-free-onepage-bootstrap-theme/ -->
          Designed by <a href="">A3H1</a>
        </div>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>